// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVg60fFKO7spGuPfP1-IUSe1vrew6XvTE',
    appId: '1:197253225414:web:f6edcff6354603a94a30c7',
    messagingSenderId: '197253225414',
    projectId: 'blog-app-flutter-2669b',
    authDomain: 'blog-app-flutter-2669b.firebaseapp.com',
    storageBucket: 'blog-app-flutter-2669b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHBK9nPYhSB98nFg6aI98ID7VJIKHdqJc',
    appId: '1:197253225414:android:03ae59c18603ae204a30c7',
    messagingSenderId: '197253225414',
    projectId: 'blog-app-flutter-2669b',
    storageBucket: 'blog-app-flutter-2669b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWFmPiGfLUfa0y7bh1dNnTk_cRlDqeB-M',
    appId: '1:197253225414:ios:0ff1365d8acd8af24a30c7',
    messagingSenderId: '197253225414',
    projectId: 'blog-app-flutter-2669b',
    storageBucket: 'blog-app-flutter-2669b.appspot.com',
    iosClientId: '197253225414-aglsqotehr5bfa3mmus1nj8uktvmfm1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWFmPiGfLUfa0y7bh1dNnTk_cRlDqeB-M',
    appId: '1:197253225414:ios:0ff1365d8acd8af24a30c7',
    messagingSenderId: '197253225414',
    projectId: 'blog-app-flutter-2669b',
    storageBucket: 'blog-app-flutter-2669b.appspot.com',
    iosClientId: '197253225414-aglsqotehr5bfa3mmus1nj8uktvmfm1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogapp',
  );
}
